/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateProduct"];
        post?: never;
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/toss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/qna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQna"];
        put?: never;
        post: operations["addQna"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/qna/{qnaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addAnswer"];
        delete: operations["deleteAnswer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addBookmark"];
        delete: operations["deleteBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/local/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addProduct_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGuide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: int64 */
            id?: number;
            email?: string;
            nickname?: string;
            password?: string;
            /** @enum {string} */
            loginType?: "LOCAL" | "KAKAO";
            userProfile?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            kakaoId?: string;
            /** Format: int32 */
            penaltyCount?: number;
            /** Format: date-time */
            deletedAt?: string;
        };
        ProductCreateRequest: {
            name: string;
            description: string;
            /** @enum {string} */
            category: "STARGOODS" | "FIGURE" | "CDLP" | "GAME";
            /** @enum {string} */
            subCategory: "ACC" | "STATIONARY" | "DAILY" | "ETC" | "ELECTRONICS" | "GAME";
            imagesFiles: string[];
        };
        ProductCreateResponse: {
            /** Format: int64 */
            productId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RsDataProductCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductCreateResponse"];
        };
        Data: {
            paymentKey?: string;
            orderId?: string;
            status?: string;
            /** Format: int64 */
            totalAmount?: number;
        };
        TossWebhookRequest: {
            eventType?: string;
            data?: components["schemas"]["Data"];
        };
        RsDataVoid: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: Record<string, never>;
        };
        RsDataObject: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: Record<string, never>;
        };
        ProductQnACreateRequest: {
            question: string;
        };
        ProductQnaCreateResponse: {
            /** Format: int64 */
            qnaId?: number;
            /** Format: int64 */
            questionerId?: number;
            question?: string;
            /** Format: date-time */
            questionedAt?: string;
        };
        RsDataProductQnaCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductQnaCreateResponse"];
        };
        ProductQnAAnswerRequest: {
            answer: string;
        };
        ProductQnAAnswerResponse: {
            /** Format: int64 */
            qnaId?: number;
            /** Format: int64 */
            answerId?: number;
            /** Format: int64 */
            answererId?: number;
            answer?: string;
            /** Format: date-time */
            answeredAt?: string;
        };
        RsDataProductQnAAnswerResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductQnAAnswerResponse"];
        };
        BookmarkCreateResponse: {
            /** Format: int64 */
            bookmarkedId?: number;
            /** Format: int64 */
            productId?: number;
            /** Format: date-time */
            bookmarkedAt?: string;
        };
        RsDataBookmarkCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BookmarkCreateResponse"];
        };
        RsDataTokenRefreshResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["TokenRefreshResponse"];
        };
        TokenRefreshResponse: {
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        LocalLoginRequest: {
            email: string;
            password: string;
        };
        LocalLoginResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        RsDataLocalLoginResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["LocalLoginResponse"];
        };
        LocalSignUpRequest: {
            email: string;
            password: string;
            nickname: string;
        };
        LocalSignUpResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
        };
        RsDataLocalSignUpResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["LocalSignUpResponse"];
        };
        EmailVerifyRequest: {
            email: string;
            code: string;
        };
        EmailVerifyResponse: {
            /** Format: date-time */
            verifiedAt?: string;
        };
        RsDataEmailVerifyResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["EmailVerifyResponse"];
        };
        EmailSendRequest: {
            email: string;
        };
        EmailSendResponse: {
            /** Format: date-time */
            sentAt?: string;
        };
        RsDataEmailSendResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["EmailSendResponse"];
        };
        UserDeleteRequest: {
            password: string;
        };
        RsDataUserDeleteResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["UserDeleteResponse"];
        };
        UserDeleteResponse: {
            deletedAt?: string;
        };
        AuctionCreateRequest: {
            /** Format: int64 */
            product_id: number;
            /** Format: int32 */
            startPrice: number;
            /** Format: int32 */
            buyNowPrice: number;
            /** Format: int32 */
            midBidStep: number;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        AuctionCreateResponse: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            product_id?: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            buyNowPrice?: number;
            /** Format: int32 */
            midBidStep?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
        };
        RsDataAuctionCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionCreateResponse"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ProductQnAListResponse: {
            /** Format: int32 */
            totalCount?: number;
            productQnAResponses?: components["schemas"]["ProductQnAResponse"][];
        };
        ProductQnAResponse: {
            productQnaCreateResponse?: components["schemas"]["ProductQnaCreateResponse"];
            answers?: components["schemas"]["ProductQnAAnswerResponse"][];
        };
        RsDataProductQnAListResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductQnAListResponse"];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        GetCurrentUserInfoResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
        };
        RsDataGetCurrentUserInfoResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["GetCurrentUserInfoResponse"];
        };
        GuideDto: {
            /** Format: int64 */
            id?: number;
            content?: string;
        };
        ProductHelpResponse: {
            guides?: components["schemas"]["GuideDto"][];
        };
        RsDataProductHelpResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductHelpResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateProduct: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductCreateResponse"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    handle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TossWebhookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query: {
                paymentId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fail: {
        parameters: {
            query: {
                user: components["schemas"]["User"];
            };
            header?: never;
            path: {
                paymentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataObject"];
                };
            };
        };
    };
    create: {
        parameters: {
            query: {
                user: components["schemas"]["User"];
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataObject"];
                };
            };
        };
    };
    addProduct: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductCreateResponse"];
                };
            };
        };
    };
    getQna: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductQnAListResponse"];
                };
            };
        };
    };
    addQna: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductQnACreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductQnaCreateResponse"];
                };
            };
        };
    };
    addAnswer: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                productId: number;
                qnaId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductQnAAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductQnAAnswerResponse"];
                };
            };
        };
    };
    deleteAnswer: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                qnaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    addBookmark: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBookmarkCreateResponse"];
                };
            };
        };
    };
    deleteBookmark: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBookmarkCreateResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTokenRefreshResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLocalLoginResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalSignUpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLocalSignUpResponse"];
                };
            };
        };
    };
    verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmailVerifyResponse"];
                };
            };
        };
    };
    sendVerificationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmailSendResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query: {
                user: components["schemas"]["User"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDeleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataUserDeleteResponse"];
                };
            };
        };
    };
    addProduct_1: {
        parameters: {
            query: {
                actor: components["schemas"]["User"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAuctionCreateResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query: {
                userId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    me: {
        parameters: {
            query: {
                user: components["schemas"]["User"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataGetCurrentUserInfoResponse"];
                };
            };
        };
    };
    getGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductHelpResponse"];
                };
            };
        };
    };
}
