/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProduct"];
        put: operations["updateProduct"];
        post?: never;
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notificationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotificationById"];
        put: operations["readNotification"];
        post?: never;
        delete: operations["deleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/help/{guideId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateGuide"];
        post?: never;
        delete: operations["deleteGuide"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/toss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prepare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/profile/img": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getProfileImageUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/paymentMethods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cardList"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/qna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQna"];
        put?: never;
        post: operations["addQna"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/qna/{qnaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addBookmark"];
        delete: operations["deleteBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/img": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getImageUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/local/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuctions"];
        put?: never;
        post: operations["addProduct_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/buy-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buyNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBidHistory"];
        put?: never;
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGuide"];
        put?: never;
        post: operations["createGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/sse/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeAuction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyBids"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuctionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/highest-bid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHighestBid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bid-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBidStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bid-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBidList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHomeAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/paymentMethods/{paymentMethodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/qna/{qnaId}/{answerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAnswer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductCreateRequest: {
            name: string;
            description: string;
            /** @enum {string} */
            category: "STARGOODS" | "FIGURE" | "CDLP" | "GAME";
            /** @enum {string} */
            subCategory: "ACC" | "STATIONARY" | "DAILY" | "ETC" | "ELECTRONICS" | "GAME";
            imagesFiles: string[];
        };
        ProductCreateResponse: {
            /** Format: int64 */
            productId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RsDataProductCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductCreateResponse"];
        };
        NotificationResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            message?: string;
            /** Format: date-time */
            sendAt?: string;
            /** Format: date-time */
            readAt?: string;
        };
        RsDataNotificationResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["NotificationResponse"];
        };
        GuideCreateRequest: {
            content: string;
        };
        GuideDto: {
            /** Format: int64 */
            id?: number;
            content?: string;
        };
        RsDataGuideDto: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["GuideDto"];
        };
        Data: {
            paymentKey?: string;
            orderId?: string;
            status?: string;
            /** Format: int64 */
            totalAmount?: number;
        };
        TossWebhookRequest: {
            eventType?: string;
            data?: components["schemas"]["Data"];
        };
        RsDataVoid: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: Record<string, never>;
        };
        RsDataObject: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: Record<string, never>;
        };
        PaymentPrepareRequest: {
            /** Format: int64 */
            winnerId?: number;
        };
        PaymentPrepareResponse: {
            /** Format: int64 */
            paymentId?: number;
            /** @enum {string} */
            status?: "REQUESTED" | "PROCESSING" | "PAID" | "FAILED" | "EXPIRED" | "CANCELED";
            autoPaid?: boolean;
            toss?: components["schemas"]["TossInfo"];
        };
        RsDataPaymentPrepareResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PaymentPrepareResponse"];
        };
        TossInfo: {
            orderId?: string;
            /** Format: int64 */
            amount?: number;
        };
        PreSignedUrlListRequest: {
            requests: components["schemas"]["PreSignedUrlRequest"][];
        };
        PreSignedUrlRequest: {
            contentType: string;
            /** Format: int64 */
            contentLength: number;
        };
        RsDataListString: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: string[];
        };
        RegisterCardRequest: {
            billingKey: string;
            /** @enum {string} */
            cardCompany: "KB" | "SHINHAN" | "HYUNDAI" | "SAMSUNG" | "LOTTE" | "NH" | "HANA" | "BC" | "WOORI";
            cardNumberMasked: string;
            cardName: string;
        };
        CardResponse: {
            /** Format: int64 */
            id?: number;
            billingKey?: string;
            /** @enum {string} */
            cardCompany?: "KB" | "SHINHAN" | "HYUNDAI" | "SAMSUNG" | "LOTTE" | "NH" | "HANA" | "BC" | "WOORI";
            cardNumberMasked?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RsDataCardResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["CardResponse"];
        };
        ProductQnACreateRequest: {
            question: string;
        };
        ProductQnaCreateResponse: {
            /** Format: int64 */
            qnaId?: number;
            /** Format: int64 */
            questionerId?: number;
            question?: string;
            /** Format: date-time */
            questionedAt?: string;
        };
        RsDataProductQnaCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductQnaCreateResponse"];
        };
        ProductQnAAnswerRequest: {
            answer: string;
        };
        ProductQnAAnswerResponse: {
            /** Format: int64 */
            qnaId?: number;
            /** Format: int64 */
            answerId?: number;
            /** Format: int64 */
            answererId?: number;
            answer?: string;
            /** Format: date-time */
            answeredAt?: string;
        };
        RsDataProductQnAAnswerResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductQnAAnswerResponse"];
        };
        BookmarkCreateResponse: {
            /** Format: int64 */
            bookmarkedId?: number;
            /** Format: int64 */
            productId?: number;
            /** Format: date-time */
            bookmarkedAt?: string;
        };
        RsDataBookmarkCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BookmarkCreateResponse"];
        };
        RsDataTokenRefreshResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["TokenRefreshResponse"];
        };
        TokenRefreshResponse: {
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        LocalLoginRequest: {
            email: string;
            password: string;
        };
        LocalLoginResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        RsDataLocalLoginResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["LocalLoginResponse"];
        };
        LocalSignUpRequest: {
            email: string;
            password: string;
            nickname: string;
        };
        LocalSignUpResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
        };
        RsDataLocalSignUpResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["LocalSignUpResponse"];
        };
        EmailVerifyRequest: {
            email: string;
            code: string;
        };
        EmailVerifyResponse: {
            /** Format: date-time */
            verifiedAt?: string;
        };
        RsDataEmailVerifyResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["EmailVerifyResponse"];
        };
        EmailSendRequest: {
            email: string;
        };
        EmailSendResponse: {
            /** Format: date-time */
            sentAt?: string;
        };
        RsDataEmailSendResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["EmailSendResponse"];
        };
        UserDeleteRequest: {
            password: string;
        };
        RsDataUserDeleteResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["UserDeleteResponse"];
        };
        UserDeleteResponse: {
            deletedAt?: string;
        };
        AuctionCreateRequest: {
            /** Format: int64 */
            product_id: number;
            /** Format: int32 */
            startPrice: number;
            /** Format: int32 */
            buyNowPrice: number;
            /** Format: int32 */
            midBidStep: number;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        AuctionCreateResponse: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            product_id?: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            buyNowPrice?: number;
            /** Format: int32 */
            midBidStep?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
        };
        RsDataAuctionCreateResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionCreateResponse"];
        };
        BuyNowRequestDto: {
            /** Format: int64 */
            bidAmount?: number;
        };
        BuyNowResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            auctionStatus?: string;
            /** Format: int64 */
            winnerId?: number;
            /** Format: int64 */
            finalPrice?: number;
            /** Format: date-time */
            winTime?: string;
        };
        RsDataBuyNowResponseDto: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BuyNowResponseDto"];
        };
        BidRequestDto: {
            /** Format: int64 */
            bidAmount: number;
        };
        BidResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            isHighestBidder?: boolean;
            /** Format: int64 */
            currentHighestBid?: number;
            /** Format: date-time */
            bidTime?: string;
        };
        RsDataBidResponseDto: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BidResponseDto"];
        };
        UpdateProfileRequest: {
            nickname?: string;
            profileImageKey?: string;
        };
        RsDataUpdateProfileResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["UpdateProfileResponse"];
        };
        UpdateProfileResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            profileImageUrl?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        MyPageResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
            profileImageUrl?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RsDataMyPageResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MyPageResponse"];
        };
        CardResponseList: {
            registerCardResponses?: components["schemas"]["CardResponse"][];
        };
        RsDataCardResponseList: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["CardResponseList"];
        };
        MyBookmarkPageResponse: {
            /** Format: int32 */
            page?: number;
            /** Format: int64 */
            total?: number;
            bookmarks?: components["schemas"]["MyBookmarkResponse"][];
        };
        MyBookmarkResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            productId?: number;
            title?: string;
            productImageUrl?: string;
            /** Format: date-time */
            bookmarkedAt?: string;
        };
        RsDataMyBookmarkPageResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MyBookmarkPageResponse"];
        };
        ProductSearchResponse: {
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            sellerId?: number;
            name?: string;
            description?: string;
            images?: string[];
            /** @enum {string} */
            category?: "STARGOODS" | "FIGURE" | "CDLP" | "GAME";
            /** @enum {string} */
            subCategory?: "ACC" | "STATIONARY" | "DAILY" | "ETC" | "ELECTRONICS" | "GAME";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int32 */
            bookmarkCount?: number;
        };
        RsDataProductSearchResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductSearchResponse"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ProductQnAListResponse: {
            /** Format: int32 */
            totalCount?: number;
            productQnAResponses?: components["schemas"]["ProductQnAResponse"][];
        };
        ProductQnAResponse: {
            productQnaCreateResponse?: components["schemas"]["ProductQnaCreateResponse"];
            answers?: components["schemas"]["ProductQnAAnswerResponse"][];
        };
        RsDataProductQnAListResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductQnAListResponse"];
        };
        RsDataListNotificationResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["NotificationResponse"][];
        };
        MyProductPageResponse: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            products?: components["schemas"]["MyProductResponse"][];
        };
        MyProductResponse: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            name?: string;
            imageUrl?: string;
            status?: string;
            /** Format: int32 */
            currentHighestBid?: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: date-time */
            endAt?: string;
            /** Format: int64 */
            bookmarkCount?: number;
            /** Format: int64 */
            bidCount?: number;
            /** Format: int64 */
            remainingTimeSeconds?: number;
        };
        RsDataMyProductPageResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MyProductPageResponse"];
        };
        MyBidPageResponse: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            auctions?: components["schemas"]["MyBidResponse"][];
        };
        MyBidResponse: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            productName?: string;
            productImageUrl?: string;
            /** Format: int32 */
            myBid?: number;
            /** Format: int32 */
            finalBid?: number;
            status?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: int64 */
            winnerId?: number;
        };
        RsDataMyBidPageResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MyBidPageResponse"];
        };
        GetCurrentUserInfoResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
        };
        RsDataGetCurrentUserInfoResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["GetCurrentUserInfoResponse"];
        };
        AuctionCursorResponse: {
            cursor?: string;
            items?: components["schemas"]["AuctionItemResponse"][];
            hasNext?: boolean;
        };
        AuctionItemResponse: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            name?: string;
            imageUrl?: string;
            status?: string;
            category?: string;
            subCategory?: string;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            currentHighestBid?: number;
            /** Format: int32 */
            bidCount?: number;
            /** Format: int32 */
            bookmarkCount?: number;
            /** Format: date-time */
            endAt?: string;
            /** Format: int64 */
            remainingTimeSeconds?: number;
            isBookmarked?: boolean;
        };
        RsDataAuctionCursorResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionCursorResponse"];
        };
        AuctionDetailResponse: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            sellerId?: number;
            sellerNickname?: string;
            name?: string;
            description?: string;
            category?: string;
            subCategory?: string;
            status?: string;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            buyNowPrice?: number;
            /** Format: int32 */
            minBidStep?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            currentHighestBid?: number;
            /** Format: int32 */
            totalBidCount?: number;
            /** Format: int64 */
            remainingTimeSeconds?: number;
            imageUrls?: string[];
            isBookmarked?: boolean;
            bidHistory?: components["schemas"]["BidHistoryResponse"][];
        };
        BidHistoryResponse: {
            /** Format: int64 */
            bidId?: number;
            /** Format: int64 */
            bidAmount?: number;
            bidder?: string;
            /** Format: date-time */
            bidTime?: string;
        };
        RsDataAuctionDetailResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionDetailResponse"];
        };
        AuctionBidUpdate: {
            /** Format: int32 */
            currentHighestBid?: number;
            bidderNickname?: string;
        };
        RsDataAuctionBidUpdate: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionBidUpdate"];
        };
        PageBidHistoryResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["BidHistoryResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        RsDataPageBidHistoryResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PageBidHistoryResponse"];
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        RsDataListBidHistoryResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BidHistoryResponse"][];
        };
        AuctionHomeResponse: {
            endingSoon?: components["schemas"]["AuctionItemResponse"][];
            popular?: components["schemas"]["AuctionItemResponse"][];
        };
        RsDataAuctionHomeResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionHomeResponse"];
        };
        ProductHelpResponse: {
            guides?: components["schemas"]["GuideDto"][];
        };
        RsDataProductHelpResponse: {
            code?: string;
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductHelpResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductSearchResponse"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductCreateResponse"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getNotificationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataNotificationResponse"];
                };
            };
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataNotificationResponse"];
                };
            };
        };
    };
    deleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    updateGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guideId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataGuideDto"];
                };
            };
        };
    };
    deleteGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guideId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    handle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TossWebhookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query: {
                paymentId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    fail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataObject"];
                };
            };
        };
    };
    prepare: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentPrepareRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPaymentPrepareResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query: {
                winnerId: number;
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataObject"];
                };
            };
        };
    };
    getProfileImageUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreSignedUrlListRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListString"];
                };
            };
        };
    };
    cardList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataCardResponseList"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataCardResponse"];
                };
            };
        };
    };
    addProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductCreateResponse"];
                };
            };
        };
    };
    getQna: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductQnAListResponse"];
                };
            };
        };
    };
    addQna: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductQnACreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductQnaCreateResponse"];
                };
            };
        };
    };
    addAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
                qnaId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductQnAAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductQnAAnswerResponse"];
                };
            };
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBookmarkCreateResponse"];
                };
            };
        };
    };
    deleteBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBookmarkCreateResponse"];
                };
            };
        };
    };
    getImageUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreSignedUrlListRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListString"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTokenRefreshResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLocalLoginResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalSignUpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLocalSignUpResponse"];
                };
            };
        };
    };
    verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmailVerifyResponse"];
                };
            };
        };
    };
    sendVerificationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmailSendResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDeleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataUserDeleteResponse"];
                };
            };
        };
    };
    getAuctions: {
        parameters: {
            query?: {
                status?: "SCHEDULED" | "LIVE" | "ENDED" | "CANCELLED";
                category?: "STARGOODS" | "FIGURE" | "CDLP" | "GAME";
                subCategory?: "ACC" | "STATIONARY" | "DAILY" | "ETC" | "ELECTRONICS" | "GAME";
                keyword?: string;
                sortType?: "NEWEST" | "CLOSING" | "POPULAR";
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAuctionCursorResponse"];
                };
            };
        };
    };
    addProduct_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAuctionCreateResponse"];
                };
            };
        };
    };
    buyNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyNowRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBuyNowResponseDto"];
                };
            };
        };
    };
    getBidHistory: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataPageBidHistoryResponse"];
                };
            };
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataBidResponseDto"];
                };
            };
        };
    };
    getGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataProductHelpResponse"];
                };
            };
        };
    };
    createGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataGuideDto"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataUpdateProfileResponse"];
                };
            };
        };
    };
    subscribeAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMyPageResponse"];
                };
            };
        };
    };
    getMyBookmarks: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMyBookmarkPageResponse"];
                };
            };
        };
    };
    getNotification: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListNotificationResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getMyProducts: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMyProductPageResponse"];
                };
            };
        };
    };
    getMyBids: {
        parameters: {
            query?: {
                page?: number;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMyBidPageResponse"];
                };
            };
        };
    };
    me_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataGetCurrentUserInfoResponse"];
                };
            };
        };
    };
    getAuctionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAuctionDetailResponse"];
                };
            };
        };
    };
    getHighestBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAuctionBidUpdate"];
                };
            };
        };
    };
    getBidStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getBidList: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListBidHistoryResponse"];
                };
            };
        };
    };
    getHomeAuctions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataAuctionHomeResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentMethodId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deleteAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
                qnaId: number;
                answerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
}
